spring:
  application:
    name: backEnd

  datasource:
    jdbc-url: jdbc:mysql://localhost:3306/Cloudbalance
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jwt:
    secret = aB3dE5Fg/7HiJ9KlMnOpQrStUvWxYz/1A2B3C4D5E6F7G8H9I=
    expiration = 86400000

  snowflake:
    url: jdbc:snowflake://YFYRZGG-BWB35436.snowflakecomputing.com/?warehouse=COMPUTE_WH&db=aws&schema=cost
    username: ro_user
    password: fRe$her@b00tc@mp2025
    driver-class-name: net.snowflake.client.jdbc.SnowflakeDriver